//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMediaClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMediaClient.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subsection.
        /// </summary>
        public static string AddSubSection {
            get {
                return ResourceManager.GetString("AddSubSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new topic.
        /// </summary>
        public static string AddTopic {
            get {
                return ResourceManager.GetString("AddTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage album settings.
        /// </summary>
        public static string AlbumSettings {
            get {
                return ResourceManager.GetString("AlbumSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all topics.
        /// </summary>
        public static string AllTopics {
            get {
                return ResourceManager.GetString("AllTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already a member.
        /// </summary>
        public static string AlreadyMember {
            get {
                return ResourceManager.GetString("AlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post anonymously.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for membership.
        /// </summary>
        public static string ApplyForMembership {
            get {
                return ResourceManager.GetString("ApplyForMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse section anonymously.
        /// </summary>
        public static string BrowseAnonymous {
            get {
                return ResourceManager.GetString("BrowseAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change main picture.
        /// </summary>
        public static string ChangeMainPicture {
            get {
                return ResourceManager.GetString("ChangeMainPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change position.
        /// </summary>
        public static string ChangePosition {
            get {
                return ResourceManager.GetString("ChangePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role of an user.
        /// </summary>
        public static string ChangePositionOfUser {
            get {
                return ResourceManager.GetString("ChangePositionOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your settings.
        /// </summary>
        public static string ChangeYourSettings {
            get {
                return ResourceManager.GetString("ChangeYourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join chat room.
        /// </summary>
        public static string ChatRoom {
            get {
                return ResourceManager.GetString("ChatRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat room.
        /// </summary>
        public static string ChatRoomName {
            get {
                return ResourceManager.GetString("ChatRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create album.
        /// </summary>
        public static string CreateAlbum {
            get {
                return ResourceManager.GetString("CreateAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group chat.
        /// </summary>
        public static string CreateGroupChat {
            get {
                return ResourceManager.GetString("CreateGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create interest.
        /// </summary>
        public static string CreateInterest {
            get {
                return ResourceManager.GetString("CreateInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create photo.
        /// </summary>
        public static string CreatePhoto {
            get {
                return ResourceManager.GetString("CreatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profile.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create section.
        /// </summary>
        public static string CreateSection {
            get {
                return ResourceManager.GetString("CreateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create topic.
        /// </summary>
        public static string CreateTopic {
            get {
                return ResourceManager.GetString("CreateTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create video.
        /// </summary>
        public static string CreateVideo {
            get {
                return ResourceManager.GetString("CreateVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPassword.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete topic.
        /// </summary>
        public static string DeleteTopic {
            get {
                return ResourceManager.GetString("DeleteTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display search section results.
        /// </summary>
        public static string DisplaySearchSectionResults {
            get {
                return ResourceManager.GetString("DisplaySearchSectionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        public static string EditComment {
            get {
                return ResourceManager.GetString("EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email link.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        public static string Everyone {
            get {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed interests.
        /// </summary>
        public static string FollowedInterests {
            get {
                return ResourceManager.GetString("FollowedInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriendsOfFriends.
        /// </summary>
        public static string FriendsOfFriends {
            get {
                return ResourceManager.GetString("FriendsOfFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View full activity.
        /// </summary>
        public static string FullActivity {
            get {
                return ResourceManager.GetString("FullActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action.
        /// </summary>
        public static string InvalidAction {
            get {
                return ResourceManager.GetString("InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest activity.
        /// </summary>
        public static string LatestActivity {
            get {
                return ResourceManager.GetString("LatestActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest friends activity.
        /// </summary>
        public static string LatestFriendsActivity {
            get {
                return ResourceManager.GetString("LatestFriendsActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make profile picture.
        /// </summary>
        public static string MakeProfilePicture {
            get {
                return ResourceManager.GetString("MakeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum age.
        /// </summary>
        public static string MaximumAge {
            get {
                return ResourceManager.GetString("MaximumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age.
        /// </summary>
        public static string MinimumAge {
            get {
                return ResourceManager.GetString("MinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod.
        /// </summary>
        public static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New friends requests.
        /// </summary>
        public static string NewFriendsRequests {
            get {
                return ResourceManager.GetString("NewFriendsRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed topics with new comments.
        /// </summary>
        public static string NewSubscribedTopics {
            get {
                return ResourceManager.GetString("NewSubscribedTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t post anonymously.
        /// </summary>
        public static string NonAnonymous {
            get {
                return ResourceManager.GetString("NonAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non permited operation.
        /// </summary>
        public static string NonPermitedOperation {
            get {
                return ResourceManager.GetString("NonPermitedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner type.
        /// </summary>
        public static string OwnerType {
            get {
                return ResourceManager.GetString("OwnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image file.
        /// </summary>
        public static string PhotoFile {
            get {
                return ResourceManager.GetString("PhotoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture successfully changed.
        /// </summary>
        public static string ProfilePictureChanged {
            get {
                return ResourceManager.GetString("ProfilePictureChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile search results.
        /// </summary>
        public static string ProfileSearchResults {
            get {
                return ResourceManager.GetString("ProfileSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage profile settings.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicity.
        /// </summary>
        public static string Publicity {
            get {
                return ResourceManager.GetString("Publicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log in.
        /// </summary>
        public static string ReferenceLogIn {
            get {
                return ResourceManager.GetString("ReferenceLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search profiles by criteria.
        /// </summary>
        public static string SearchProfilesByCriteria {
            get {
                return ResourceManager.GetString("SearchProfilesByCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections you are member of.
        /// </summary>
        public static string SectionsMember {
            get {
                return ResourceManager.GetString("SectionsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select members.
        /// </summary>
        public static string SelectMembers {
            get {
                return ResourceManager.GetString("SelectMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select position.
        /// </summary>
        public static string SelectPosition {
            get {
                return ResourceManager.GetString("SelectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat.
        /// </summary>
        public static string StartChat {
            get {
                return ResourceManager.GetString("StartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed topics.
        /// </summary>
        public static string SubscribedTopics {
            get {
                return ResourceManager.GetString("SubscribedTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted.
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended until.
        /// </summary>
        public static string SuspendedUntil {
            get {
                return ResourceManager.GetString("SuspendedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend user.
        /// </summary>
        public static string SuspendUser {
            get {
                return ResourceManager.GetString("SuspendUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string UnmatchingPassword {
            get {
                return ResourceManager.GetString("UnmatchingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View unread messages.
        /// </summary>
        public static string UnreadMessages {
            get {
                return ResourceManager.GetString("UnreadMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update settings.
        /// </summary>
        public static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your profile.
        /// </summary>
        public static string UpdateYourProfile {
            get {
                return ResourceManager.GetString("UpdateYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See uploaded videos.
        /// </summary>
        public static string UploadedVideos {
            get {
                return ResourceManager.GetString("UploadedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload video.
        /// </summary>
        public static string UploadVideo {
            get {
                return ResourceManager.GetString("UploadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select video file.
        /// </summary>
        public static string VideoFile {
            get {
                return ResourceManager.GetString("VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all comments in this section.
        /// </summary>
        public static string ViewAllComments {
            get {
                return ResourceManager.GetString("ViewAllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all topics in this section.
        /// </summary>
        public static string ViewAllTopics {
            get {
                return ResourceManager.GetString("ViewAllTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your profile.
        /// </summary>
        public static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View whole topic.
        /// </summary>
        public static string WholeTopic {
            get {
                return ResourceManager.GetString("WholeTopic", resourceCulture);
            }
        }
    }
}
